plugin:
  id: msfragger-curtainptm-converter
  name: MSFragger to CurtainPTM Converter
  description: "Convert MSFragger PTM single site output to CurtainPTM upload format. Extracts PTM positions from index columns, maps peptide sequences to proteins, and generates sequence windows around modification sites. Based on: Phung et al. (2024) PNAS 121(7):e2312676121. Repository: https://github.com/noatgnu/curtain-utils"
  version: 1.0.0
  author: CauldronGO Team
  category: utilities
  subcategory: format-conversion
  icon: transform
  repository: https://github.com/noatgnu/msfragger-curtainptm-converter-plugin

runtime:
  environments:
    - python
  entrypoint: convert.py

inputs:
  - name: input_file
    label: MSFragger Output File
    type: file
    required: true
    accept: .txt,.tsv
    description: MSFragger PTM output file containing differential analysis with site information in the Index column

  - name: index_col
    label: Index Column Name
    type: text
    required: true
    default: Index
    placeholder: Index
    description: Column name containing site information with accession ID and PTM position (e.g., P12345_S123)

  - name: peptide_col
    label: Peptide Column Name
    type: text
    required: true
    default: Peptide
    placeholder: Peptide
    description: Column name containing peptide sequences

  - name: fasta_file
    label: FASTA File (Optional)
    type: file
    required: false
    accept: .fasta,.fa
    description: Protein sequence FASTA file. If not provided, sequences will be fetched from UniProt automatically.

  - name: get_position_from_peptide
    label: Parse Position from Peptide Column
    type: boolean
    required: false
    default: false
    description: Enable this to extract PTM position from lowercase residues in the peptide sequence instead of the index column

  - name: uniprot_columns
    label: UniProt Data Columns
    type: text
    required: false
    default: accession,id,sequence,protein_name
    placeholder: accession,id,sequence,protein_name
    description: Comma-separated list of UniProt columns to retrieve when fetching sequences online

  - name: output_filename
    label: Output Filename
    type: text
    required: false
    default: curtainptm_input.txt
    placeholder: curtainptm_input.txt
    description: Name of the output file (will be created in the output folder)

  - name: sequence_window_size
    label: Sequence Window Size
    type: number
    required: false
    default: 21
    min: 1
    max: 101
    step: 2
    description: Size of the sequence window around modification sites (must be odd number). Default is 21 (10 residues before + modification + 10 after).

outputs:
  - name: converted_file
    path: '*.txt'
    type: data
    format: tsv
    description: Converted file in CurtainPTM upload format with PTM positions, sequence windows, and protein annotations

execution:
  outputDir: --output_folder
  requirements:
    pythonRequirementsFile: requirements.txt
    python: '>=3.10'
